### ISSUE TITLE
Project Proposals

### ISSUE THREAD

**Issue by MarkHoeber** [MarkHoeber/tools-tech-syllabus#29]
Please add your project proposal here.  Include:

- Technology you intend to use.
- Content summary.
- Your partner.

**Comment by Carolynjp** [comment]
Hello Mark, 

Are there any examples of projects?  I'm  interested to see one which will help me better understand the process and start thinking of ideas for one.  Thank you.  Carolyn

**Comment by MarkHoeber** [comment]
@Carolynjp I will get and share some past ones.
