### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by MarkHoeber** [MarkHoeber/tools-tech-syllabus#53]
Any questions, comments on HTML?

**Comment by MarkHoeber** [comment]
Short video showing how to open and edit the index.html file in GitHub:  https://www.youtube.com/watch?v=k-6_J7-OM5w

**Comment by LJSchmidt** [comment]
Mark, I can't tell but I may have changed your repository!  I forked it, made changes (I thought on my own GitHub account) but now I can't view my changes and it says that I am one commit ahead of you.

**Comment by MarkHoeber** [comment]
@LJSchmidt all is fine, you did a great job.  And don't worry, you cannot change **my** version of the repository without my cooperation. 

You forked the repository, which makes a separate (but connected) copy of my repository in your own account. It looks like you modified index.html and committed the changes perfectly. I see the changes in here from one commit:
  
https://github.com/LJSchmidt/get_started_html/blob/master/index.html

I tried opening your web page at:  https://ljschmidt.github.io/get_started_html/ but I got an error that says it cannot be found. I believe this means you have to do the steps here:  http://tools-tech-syllabus.readthedocs.io/en/latest/html.html#view-your-work

You should then be able to see your web page live. And you'll be able to make more changes to the index.html file as you wish.  

let me know if a video would be helpful for that part.

**Comment by LJSchmidt** [comment]
That did it, thank you!  The steps were perfectly clear.

**Comment by MarkHoeber** [comment]
All, if your image is not showing on your webpage, my guess is because the "path" to the image file is not right.

Check out this article and let me know if you want further explanation.

http://www.w3schools.com/html/html_filepaths.asp

**Comment by MarkHoeber** [comment]
All, when you add an image, by default it will be the size of the image file in HTML.  You can change that, especially if the image looks very large. Just add a "width" attribute to the image tag. Such as:

<p><img src="IMG_4929.JPG" width="50%"/></p>

You can experiment with the size and see how it looks. You can use %, or specify the number of pixels, such as:

<p><img src="IMG_4929.JPG" width="500px"/></p>

**Comment by MarkHoeber** [comment]
All, I posted a short video that demos how to set up GitHub pages to publish your index.html file as your website:

https://www.youtube.com/watch?v=AB3KmrHWzLs

**Comment by LJSchmidt** [comment]
I still can't get my photo to display on the web page.  Have any of you been successful with that?  I would appreciate any hints.

**Comment by JoanneGibson** [comment]
Hi Leah
Did you upload your photo into the GitHub folder for the getting started repository? There is an upload files button on the top right hand side. You can search for your pick to upload, or just drag it into the upload window.
FYI This is how mine looked <p><img src="IMG_20161105_105930.jpg" height=380 width=500 align=left/></p>
I had to change the dimensions because it was huge.

**Comment by JoanneGibson** [comment]
Hi Leah
Did you upload your photo into the GitHub folder for the getting started repository? There is an upload files button on the top right hand side. You can search for your pick to upload, or just drag it into the upload window. Mine was huge and so I had to change the dimensions.

**Comment by JoanneGibson** [comment]
I emailed the code I used to you. I tried to post it here but then it just tried to upload the photo into the reply box.

**Comment by MarkHoeber** [comment]
@LJSchmidt   I looked at your HTML.  It's a relative path issues.  The image and the html file are in the same directory, so no folder in the image source path is needed.  You have "get_started_html/Jan2017.jpg" . so it's looking in a subfolder called get_started_html/.  Just take that out and have the file name only

**Comment by LJSchmidt** [comment]
Finally got the picture thing!  I had not capitalized the .jpg extension in the html code while it was capitalized in the folder name.  Once they matched exactly, it came up.
