### ISSUE TITLE
RST Files

### ISSUE THREAD

**Issue by LJSchmidt** [MarkHoeber/tools-tech-syllabus#57]
I can't figure out how to upload my written RST text to my branched repository.  I tried several methods, but it keeps putting my rst text in exactly as written without recognizing the  formatting.  I have only had success when directly editing your topics sheet, but then I'm limited to one "page" because I can't copy the file or change the name.  All the files I have tried to add just repeat the characters w/o doing the formatting.  I also tried saving my online-editor text into a Word document, and adding that file, but then GitHub just sees it as a Word file to open.  Help!

**Comment by MarkHoeber** [comment]
@LJSchmidt   lt looks like you successfully added text in the branch rst_templates.  I'm not sure what other formatting you're looking for.  For example, in here, the RST syntax is displayed in the view with numbering, headings, etc:  https://github.com/LJSchmidt/rst_templates/blob/RST-assignment/tempcal2.rst

Can you be more specific about a file and specific problem with it?

**Comment by LJSchmidt** [comment]
I didn't realize that I had to name my new file with the .rst extension.  Jo clued me into that, and then there was progress!  
Now I'm having trouble with substitution.  Do you have any examples in your syllabus?  I was looking through there for a real-life example, because I don't know where to place the elements in my pages.

**Comment by MarkHoeber** [comment]
Substitutions:

In the syllabus, I have substitutions defined in the substitutions.rst file:  https://github.com/MarkHoeber/tools-tech-syllabus/blob/master/source/substitutions.rst

The substitutions.rst file in automatically included in every other RST file in the project by the following lines in the conf.py file:

```
rst_epilog = """
.. include:: substitutions.rst
"""
```

The epilog setting is the equivelent of automatically adding the include command in every RST file.  The substitutions must be accessible in every file in which they are used -- so in the processing of a RST file, the substitutions.rst file is included.

Substitutions are used in various places.  See line 40 of this file for the |Assignment| substitution:  https://github.com/MarkHoeber/tools-tech-syllabus/blob/master/source/rst.rst

Hope that helps -- there are many ways of "architecting" substitutions, this is just one.

**Comment by MarkHoeber** [comment]
I created this video on creating a Read the Docs site from your RST files  and Sphinx project:  https://www.youtube.com/watch?v=4rAoOcxQKoY
