### ISSUE TITLE
Wordpress Sites

### ISSUE THREAD

**Issue by MarkHoeber** [MarkHoeber/tools-tech-syllabus#58]
Add URLs for wordpress sites here

**Comment by seferello** [comment]
seferello.co 
:)

**Comment by LJSchmidt** [comment]
https://culturalstewblog.wordpress.com/
I will add more content at some point!

**Comment by JoanneGibson** [comment]
https://girlscouts2017.wordpress.com/
 
 Most of the content so far is under 
-Daisies, Daisy petals, Be a sister to every girl scout, and
-Brownies, inventor badge.
I started with a different webpage, but abandoned it and moved to this one called 'Growing Girls'. I couldn't figure out how to delete the other one.
 
 Thanks!

**Comment by Carolynjp** [comment]
Mine is still a work in progress. 
[]([https://carrie223.wordpress.com/]()
