### ISSUE TITLE
DITA questions

### ISSUE THREAD

**Issue by LJSchmidt** [MarkHoeber/tools-tech-syllabus#59]
I tried to work off of the "task" template to build an unordered equipment list for my topic.  Oxygen has flagged it for "unexpected element <ul>" and gives some formatting jargon that makes no sense to me.  I kept the task-d, title, short description, taskbody, and context elements.  Are any or all of those incompatible since I only need an unordered list?

**Comment by MarkHoeber** [comment]
Hi @LJSchmidt   can you share the file here?

**Comment by LJSchmidt** [comment]
I figured out after a while that it should be a concept, not a task.  That brought up new formatting problems though, it still doesn't like several things.  Right now it says 'Invalid attribute for "class" attribute.  Attribute not specified'  and 'Element type "conbody" must be declared.'  I don't know how to share the Oxygen file though.  I may just have to show you in class, if we have time.  I just keep on changing problems.
