### ISSUE TITLE
Introductions

### ISSUE THREAD

**Issue by MarkHoeber** [MarkHoeber/tools-tech-syllabus#6]
Please introduce yourself in a comment on this issue.

**Comment by JoanneGibson** [comment]
Hi there, I am Joanne Gibson. I just completed the first semester of the technical writing course at MCC and I am excited to start the tools and technologies part of the course. I look forward to meeting you all!

**Comment by Techwriter2017** [comment]
Hi.  I am Cathie Ryan and I am a new student at MCC.  Can't wait to learn about the writing tools and technologies and to meet all of you.

**Comment by seferello** [comment]
Hi everyone, my name is Samantha. I'm a new student who stumbled onto this MCC program, so I look forward to meeting everyone and getting started :)

**Comment by maestein** [comment]
Hello! My name is Mae. I've got a background in Marketing and am taking this class to help get into more technical roles.

**Comment by Carolynjp** [comment]
Hello!

My name is Carolyn and I am looking forward to learning new tools for technical writing.  I am also looking forward to collaborating with you.

**Comment by LJSchmidt** [comment]
Hi everyone!  I'm Leah- the one who didn't do the homework....  I'll do better next time.  It was great meeting all of you last night.

**Comment by cathyputnam** [comment]
Hello! I'm Cathy. I'm looking to get back into technical writing. I just got back from Dominica. :)

**Comment by Carolynjp** [comment]
My email address is carolynpalo@gmail.com

**Comment by cathyputnam** [comment]
Hi Mark-

I am wondering if you can forward the following email to the class? That 
way, you don't have to forward every email to the class. thanks so much! -C

++++++++++++++++++

Hi Everyone-

If you get a chance, send your email address to 
cathy_putnam@comcast.net. That way, I'll have everyone's email address 
so we can all keep in touch (I'll forward the combined email list to the 
group).  Hopefully we can all get together for lunch this summer sometime.

Good luck on your continuing education and/or job search! It was nice to 
meet everyone!

Cathy
